version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: marketplace_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - ./.postgres_data:/var/lib/postgresql/data

  postgres-test:
    image: postgres:latest
    container_name: marketplace_container_test
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5434:5432"

  redis:
    image: bitnami/redis:latest
    container_name: marketplace_redis
    environment:
      REDIS_PASSWORD: caduredis
    ports:
      - "6379:6379"
